import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const onest = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <main className="h-full w-full flex min-h-screen">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
